---
title: "Data Import"
author: "Alicia Yang"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(readxl)
```

## Load in dataset

```{r}
##reads in a dataset
##general rule, use relative path, NOT absolute path 
litters_data = read_csv(file = "./data/FAS_litters.csv")
##col_double = parsed as number vector
litters_data = janitor::clean_names(litters_data)
##take janitor & rewriting data 
```


##Load in pups data

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
##making clear that clean_names function is in janitor function; can also do a library(janitor) so don't have to specify 
tail(pups_data)
skimr::skim(pups_data)
```

##Play with column parsing

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
##if have space in between for column names, include backticks around words
##read_csv bring in under tibble, read.csv is regular dataset; tibble crankier
litters_data$Litt
##don't use dollar sign
class(pull(litters_data,Group))
```

##Read in an excel file

```{r}
mlb11_data = read_excel("./data/mlb11.xlsx")
```

##Read in SAS dataset

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```

##Exporting dataset
```{r}
write_csv(mlb11_Data_subset, path = "./data/mlb_subset.csv)
#use write_csv, not write.csv
```
